services:
  - type: web
    name: fgd-motors
    env: python
    buildCommand: pip install --upgrade pip && pip install -r requirements.txt
    startCommand: gunicorn wsgi:app
    envVars:
      - key: FLASK_APP
        value: app_final.py
      - key: FLASK_ENV
        value: production
      - key: PYTHON_VERSION
        value: 3.9.18
    healthCheckPath: /
